Add code coverage and sonarcloud analysis
MieuxVoter/majority-judgment-library-java pull request #14
Opened 2021-05-31 12:36 UTC by jeanpic

Modified workflow to include code coverage and sonarcloud analysis.

2021-05-31 13:43 UTC, guhur commented
Hi @jeanpic thanks a lot for your contribution! Java 8 is unfortunately a requirement for us. Do you think a work-around would exist to use Java 8?

2021-05-31 14:26 UTC, jeanpic commented
What could be done is doing the sonar analysis only with JDK 11 but still build and test with the JDK 8 I suppose. Any specific reason why you need JDK 8 ?

2021-05-31 14:49 UTC, guhur commented
Several people who are using the releases are still on Java 8. So basically, we need to provide releases + CI for Java 8.
I think your suggestion is great, but it sounds a bit weird to do only the sonar analysis on JDK11. 

Maybe we could do the following?

JDK 11: sonar analysis + build + test
JDK 8: build + test

Apparently, the [Github CI works fine with multiple versions of JDK8](https://github.com/actions/setup-java#testing-against-different-java-versions)

2021-05-31 15:12 UTC, domi41 commented
First of all, thanks !  :partying_face: 

> was there a good reason for two different configurations

No.  I experimented with both maven and gradle, and with eclipse presets.  What you saw is probably the BOOP (Bits Out Of Place) of my newcomer's journey.  Thanks for noticing it and fixing it !  It's best to have a single source of truth.

> Any specific reason why you need JDK 8

Some of our early adopters expressed the need for Java 8.
We should make sure that tests pass with that java version, but code coverage can use any.

---

Thanks again !  I'm eager to see our coverage and add some more tests to get to the 90' !

2021-05-31 15:22 UTC, domi41 approved these changes
Doing both java 8 and 11 will either require serious duplication or YAML pointer shenanigans (if those even work at all).

I'm okay for doing the grunt work if you wanna stop there.
I think for the CI to pass we'll need to put some sonarcloud keys in the env.

2021-05-31 15:28 UTC, jeanpic commented
Setting Java 8 as source and target should be enough, no need to build it with the JDK 8.

Yes to make it work you'll need to create a sonarcloud account, create a new project, update the project id and organization properties in the pom.xml and add the SONAR_TOKEN secret.

2021-06-01 10:52 UTC, domi41 commented
Sonarcloud won't let me import this project.
I think the organization MieuxVoter already exists in sonarcloud and I'm not the admin either, so I can't pursue.

@guhur , do you know who has the keys to the toolshed ?

2021-06-01 12:55 UTC, guhur commented
I just added you as an admin to the Mieux Voter group

On Tue, Jun 1, 2021 at 12:52 PM Dominique Merle ***@***.***>
wrote:

> Sonarcloud won't let me import this project.
> I think the organization MieuxVoter already exists in sonarcloud and I'm
> not the admin either, so I can't pursue.
>
> @guhur <https://github.com/guhur> , do you know who has the keys to the
> toolshed ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/MieuxVoter/majority-judgment-library-java/pull/14#issuecomment-852028002>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AC52MDWHAEOCPUYH54ITBGTTQS3XRANCNFSM452Z37WQ>
> .
>

2021-06-01 23:49 UTC, domi41 requested changes
Let's try this for size, shall we?

2021-06-01 23:49 UTC, domi41 commented on pom.xml
> +    <sonar.projectKey>jeanpic_majority-judgment-library-java</sonar.projectKey>
```suggestion
    <sonar.projectKey>MieuxVoter_majority-judgment-library-java</sonar.projectKey>
```

2021-06-01 23:49 UTC, domi41 commented on pom.xml
> +    <sonar.organization>jeanpic</sonar.organization>
```suggestion
    <sonar.organization>mieuxvoter</sonar.organization>
```

2021-06-16 06:24 UTC, domi41 commented
Thanks for the commits !

We're ready to merge, aren't we?

I see a :

```
Error:  Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.0.2155:sonar (default-cli) on project majority-judgment: You're not authorized to run analysis. Please contact the project administrator. -> [Help 1]
```

We have a `SONAR_TOKEN` though.

2021-06-16 06:25 UTC, domi41 approved these changes

2023-02-18 04:52 UTC, merged